name: test to go

on:
  push:
    tags:
      - '*'

jobs:
  publish_backend_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Get current Git tag
        id: get_tag
        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        env:
          VERSION: ${{ env.TAG }}
        run: cd backend && gradle jib --image aa/nest2d
